### ISSUE TITLE
Implement compliance work data entry pages

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/air-web#138]
Implement the following pages for each work type:

| Work Type         | Add | Edit | Close/Reopen | Delete/Restore |
| ----------------- | :-: | :--: | :----------: | :------------: |
| ACC               | ✅  |  ✅  |      ✅      |       ✅       |
| Inspection        | ✅  |  ✅  |      ✅      |       ✅       |
| Notification      | ✅  |  ✅  |      ✅      |       ✅       |
| Permit Revocation | ✅  |  ✅  |      ✅      |       ✅       |
| Report            | ✅  |  ✅  |      ✅      |       ✅       |
| RMP Inspection    | ✅  |  ✅  |      ✅      |       ✅       |

(STR work is tracked in #140.)

As part of this effort, define resource-based operations for each DTO and implement resource-based authorization handlers and validators.

### IAIP Forms

<details>
<summary>ACC</summary>

![image](https://github.com/user-attachments/assets/17af9ad5-14ce-4981-b45d-5f3578d2c2b1)
</details>

<details>
<summary>Inspection/RMP</summary>

![image](https://github.com/user-attachments/assets/eed32f71-9efc-48fc-8a4b-f0d23e8000ba)
</details>

<details>
<summary>Notification</summary>

![image](https://github.com/user-attachments/assets/e358b249-a247-4c72-99d3-ec629beffd3b)
</details>

<details>
<summary>Permit Revocation</summary>

![image](https://github.com/user-attachments/assets/40bb885c-ae91-4b9d-9e24-7fd5a9c69182)
</details>

<details>
<summary>Report</summary>

![image](https://github.com/user-attachments/assets/84230af0-1fc5-4b6c-8188-087899311ebf)
</details>

```[tasklist]
### Tasks
- [ ] https://github.com/gaepdit/air-web/issues/141
- [ ] https://github.com/gaepdit/air-web/issues/143
- [ ] https://github.com/gaepdit/air-web/issues/144
- [ ] https://github.com/gaepdit/air-web/issues/149
- [ ] https://github.com/gaepdit/air-web/issues/142
```
