### ISSUE TITLE
Deploy for data migration UAT - air-web

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/air-web#186]
Update test server to prepare for data migration UAT.

```[tasklist]
### Tasks
- [ ] Configure Azure App for authentication.
- [ ] Refresh the UAT airbranch database.
- [ ] Create new database with app and migration DB accounts.
- [ ] Run data migration scripts.
```
