### ISSUE TITLE
Plan site map and navigation

### ISSUE THREAD

**Issue by Onome88** [gaepdit/air-web#20]
```[tasklist]
### Tasks
- [x] Plan compliance monitoring and FCE site map
- [x] Plan basic enforcement site map
- [x] Plan remainder of site map
- [x] Plan navigation menu
```
