### ISSUE TITLE
Implement the new case file workflow

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/air-web#213]
```[tasklist]
### Tasks
- [x] Begin Enforcement button (facility page)
- [x] Begin Enforcement button (compliance event page)
- [x] Add Case File page
```

<details><summary>Create Enforcement buttons</summary>

![Image](https://github.com/user-attachments/assets/01e226a3-f4cc-4f88-983a-fc12a30df095)

![Image](https://github.com/user-attachments/assets/f336a7b1-3b82-440a-9221-54eabbe8b9cf)

</details> 

<details><summary>New Case File form</summary>

![Image](https://github.com/user-attachments/assets/1c9f11aa-ca33-4888-8aa0-f6fbf772e558)

</details>
