### ISSUE TITLE
Design and develop compliance work search pages

### ISSUE THREAD

**Issue by Onome88** [gaepdit/air-web#27]
```[tasklist]
### Tasks
- [ ] https://github.com/gaepdit/air-web/issues/125
- [ ] https://github.com/gaepdit/air-web/issues/127
- [x] https://github.com/gaepdit/air-web/issues/126
- [ ] https://github.com/gaepdit/air-web/issues/128
```

Here's what we're replacing:
![image](https://github.com/user-attachments/assets/ad406bc2-b880-4987-84dc-7610cf7370a6)

Here are some useful resources:

- [Checkboxes in a Razor Pages Form | Learn Razor Pages](https://www.learnrazorpages.com/razor-pages/forms/checkboxes)
- [ASP.NET Core/Razor pages working with Checkboxes - DEV Community](https://dev.to/karenpayneoregon/aspnet-corerazor-pages-working-with-checkboxes-3ck4)
- [Checks and radios · Bootstrap v5.3](https://getbootstrap.com/docs/5.3/forms/checks-radios/#checks)
- [asp.net - How to combine usage of asp-all-route-data and a list of ids in query string - Stack Overflow](https://stackoverflow.com/questions/64760438/how-to-combine-usage-of-asp-all-route-data-and-a-list-of-ids-in-query-string)

**Comment by dougwaldron** [comment]
Here are some useful resources:

- [Checkboxes in a Razor Pages Form | Learn Razor Pages](https://www.learnrazorpages.com/razor-pages/forms/checkboxes)
- [ASP.NET Core/Razor pages working with Checkboxes - DEV Community](https://dev.to/karenpayneoregon/aspnet-corerazor-pages-working-with-checkboxes-3ck4)
