### ISSUE TITLE
Deploy for QA - functionality - air-web

### ISSUE THREAD

**Issue by Onome88** [gaepdit/air-web#34]
Deploy to dev server to prepare for QA.

```[tasklist]
### Tasks
- [x] Configure IIS on server.
- [x] Create Web Deploy publish profile.
- [x] Create server-specific settings and config files.
- [x] Deploy app to server.
```

**Comment by dougwaldron** [comment]
Split issue scope with #185.
