### ISSUE TITLE
Deploy for UAT - air-web

### ISSUE THREAD

**Issue by Onome88** [gaepdit/air-web#37]
Deploy to the test server and prepare for UAT.

```[tasklist]
### Tasks
- [x] Configure IIS on server.
- [x] Create Web Deploy publish profile.
- [x] Create server-specific settings and config files.
- [x] Deploy app to server.
```
