### ISSUE TITLE
Define compliance DTOs and services

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/air-web#54]
```[tasklist]
### Tasks
- [x] Define Facility DTO/service
- [x] Define FCE DTOs and services
- [x] Define compliance monitoring DTOs and services
```
